project_name: exoscale-cli

builds:
  - binary: exo
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - windows
      - darwin
      - linux
      - openbsd

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

    ignore:
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64

    hooks:
      pre: make manpages completions

archives:
  - id: windows
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - contrib/completion/**/*
      - manpage/*

release:
  github:
    owner: exoscale
    name: cli
  draft: true

nfpms:
  - vendor: Exoscale
    homepage: https://www.exoscale.com/
    maintainer: Exoscale Support <support@exoscale.com>
    description: Manage (almost) everything at Exoscale from the command line.
    license: Apache 2.0
    formats:
      - deb
      - rpm
    files:
      "./manpage/exo*.1": "/usr/share/man/man1"
      "./contrib/completion/bash/exo": "/etc/bash_completion.d/exo"

brews:
  - github:
      owner: exoscale
      name: homebrew-tap
    folder: Formula
    homepage: "https://exoscale.github.io/cli/"
    description: Manage (almost) everything at Exoscale from the command line.
    install: |
      bin.install "exo"
      man1.install Dir["manpage/exo*.1"]
      bash_completion.install "contrib/completion/bash/exo"
