project_name: exoscale-cli

before:
  hooks:
    - make manpages completions

builds:
  - binary: exo
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - windows
      - darwin
      - linux
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64

archives:
  - id: windows
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - contrib/completion/**/*
      - manpage/*

nfpms:
  - vendor: Exoscale
    homepage: https://www.exoscale.com/
    maintainer: Exoscale Support <support@exoscale.com>
    description: Manage easily your Exoscale infrastructure from the command-line.
    license: Apache 2.0
    formats:
      - deb
      - rpm
    contents:
      # manpages
      - src: "./manpage/exo*.1"
        dst: "/usr/share/man/man1"
      # bash
      - src: "./contrib/completion/bash/exo"
        dst: "/usr/share/bash-completion/completions/exo"
      # zsh
      - src: "./contrib/completion/zsh/_exo"
        dst: "/usr/share/zsh/vendor-completions/_exo"
