project_name: exoscale-cli

builds:
  - binary: exo
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - windows
      - darwin
      - linux
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
    hooks:
      pre: make manpages completions sos-certificates

archives:
  - id: windows
    format_overrides:
      - goos: windows
        format: zip
    files:
      - sos-certs.pem
      - LICENSE
      - contrib/completion/**/*
      - manpage/*

release:
  github:
    owner: exoscale
    name: cli
  draft: true

nfpms:
  - vendor: Exoscale
    homepage: https://www.exoscale.com/
    maintainer: Exoscale Support <support@exoscale.com>
    description: Manage easily your Exoscale infrastructure from the command-line.
    license: Apache 2.0
    formats:
      - deb
      - rpm
    contents:
      # manpages
      - src: "./manpage/exo*.1"
        dst: "/usr/share/man/man1"
      # bash
      - src: "./contrib/completion/bash/exo"
        dst: "/usr/share/bash-completion/completion/exo"
      # fish
      - src: "./contrib/completion/fish/exo.fish"
        dst: "/usr/share/fish/vendor_functions.d/exo.fish"
      # zsh
      - src: "./contrib/completion/zsh/_exo"
        dst: "/usr/share/zsh/vendor-completions/_exo"

brews:
  - tap:
      owner: exoscale
      name: homebrew-tap
    folder: Formula
    homepage: "https://exoscale.github.io/cli/"
    description: Manage easily your Exoscale infrastructure from the command-line.
    install: |
      bin.install "exo"
      man1.install Dir["manpage/exo*.1"]
      bash_completion.install "contrib/completion/bash/exo"
      fish_completion.install "contrib/completion/fish/exo.fish"
      zsh_completion.install "contrib/completion/zsh/_exo"

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "exoscale/cli:latest"
      - "exoscale/cli:{{ .Major }}"
      - "exoscale/cli:{{ .Major }}.{{ .Minor }}"
      - "exoscale/cli:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - --pull
      - --build-arg="VERSION={{.Version}}"
      - --build-arg="VCS_REF={{.ShortCommit}}"
      - --build-arg="BUILD_DATE={{.Date}}"
    skip_push: auto
