builds:
  - binary: exo
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    goos:
      - windows
      - darwin
      - linux
      - openbsd

    goarch:
      - amd64

sign:
  cmd: gpg
  args: ["-u", "ops@exoscale.ch", "--detach-sign", "${artifact}"]
  artifacts: all

archive:
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE

release:
  github:
    owner: exoscale
    name: cli
  draft: true

nfpm:
  vendor: Exoscale
  homepage: https://www.exoscale.com/
  maintainer: Exoscale Support <support@exoscale.com>
  description: Manage (almost) everything at Exoscale from the command line.
  license: Apache 2.0
  formats:
    - deb
    - rpm

brew:
  name: "exo"
  github:
    owner: exoscale
    name: homebrew-tap
  folder: Formula
  homepage: "https://exoscale.github.io/cli/"
  description: Manage (almost) everything at Exoscale from the command line.
  dependencies:
      - go
  skip_upload: true

