builds:
  - binary: exo
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    goos:
      - windows
      - darwin
      - linux
      - openbsd

    goarch:
      - amd64

    hooks:
      pre: make manpage bash_completion

sign:
  cmd: gpg
  args: ["-u", "ops@exoscale.ch", "--detach-sign", "${artifact}"]
  artifacts: all

archive:
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - bash_completion
    - manpage/*

release:
  github:
    owner: exoscale
    name: cli
  draft: true

nfpm:
  vendor: Exoscale
  homepage: https://www.exoscale.com/
  maintainer: Exoscale Support <support@exoscale.com>
  description: Manage (almost) everything at Exoscale from the command line.
  license: Apache 2.0
  formats:
    - deb
    - rpm

  overrides:
    deb:
      files:
        "./manpage/exo*.1.gz": "/usr/share/man/man1"
        "./bash_completion": "/etc/bash_completion.d/exo"
    rpm:
      files:
        "./manpage/exo*.1.gz": "/usr/share/man/man1"
        "./bash_completion": "/etc/bash_completion.d/exo"

brew:
  name: "exo"
  github:
    owner: exoscale
    name: homebrew-tap
  folder: Formula
  homepage: "https://exoscale.github.io/cli/"
  description: Manage (almost) everything at Exoscale from the command line.
