ARG EXOSCALE_DOCKER_REGISTRY=registry.internal.exoscale.ch

FROM ${EXOSCALE_DOCKER_REGISTRY}/exoscale/ubuntu:jammy

RUN echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
RUN set -xe \
    && apt-get update -q \
    && apt-get install -y -q build-essential git rsync golang goreleaser \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY build-release.sh /

CMD ["/build-release.sh"]
