// AI-generated by claude-opus-5-5 - not reviewed yet
package cmd

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	v3 "github.com/exoscale/egoscale/v3"
	"github.com/exoscale/egoscale/v3/credentials"
	"github.com/stretchr/testify/require"
)

// apiErrorFor returns the error egoscale produces when the API answers a
// create-key-store request with the given status and JSON body.
func apiErrorFor(t *testing.T, status int, body string) error {
	t.Helper()

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(status)
		_, _ = w.Write([]byte(body))
	}))
	t.Cleanup(srv.Close)

	client, err := v3.NewClient(credentials.NewStaticCredentials("key", "secret"))
	require.NoError(t, err)
	_, err = client.WithEndpoint(v3.Endpoint(srv.URL)).CreateKeyStore(context.Background(), v3.CreateKeyStoreRequest{
		Name:  "ks",
		Proxy: &v3.KeyStoreProxy{Endpoint: "https://xks.example.com", Auth: &v3.KeyStoreProxyAuth{Key: "ak", Secret: "sk"}},
	})
	require.Error(t, err)
	return err
}

func TestFormatError_XKSProxyError(t *testing.T) {
	err := apiErrorFor(t, http.StatusBadRequest, `{
		"detail": "proxy health request returned XKS proxy error AuthenticationFailedException",
		"status": 400,
		"title": "Key store proxy request failed",
		"type": "#/key-store/proxy-request-failed",
		"xks-proxy-error": {"error-name": "AuthenticationFailedException"}
	}`)
	require.Equal(t,
		"Bad Request: Key store proxy request failed: proxy health request returned XKS proxy error AuthenticationFailedException"+
			"\n  - XKS proxy error: AuthenticationFailedException",
		formatError(err))

	err = apiErrorFor(t, http.StatusBadRequest, `{
		"detail": "proxy health request returned XKS proxy error AuthenticationFailedException",
		"status": 400,
		"title": "Key store proxy request failed",
		"type": "#/key-store/proxy-request-failed",
		"xks-proxy-error": {"error-name": "AuthenticationFailedException", "error-message": "invalid signature"}
	}`)
	require.Contains(t, formatError(err), "\n  - XKS proxy error: AuthenticationFailedException: invalid signature")
}

func TestFormatError_WithoutXKSProxyError(t *testing.T) {
	err := apiErrorFor(t, http.StatusBadRequest, `{
		"detail": "create-key-store is disabled",
		"status": 400,
		"title": "Invalid argument",
		"type": "#/invalid-argument"
	}`)
	require.Equal(t, "Bad Request: Invalid argument: create-key-store is disabled", formatError(err))
}
