name: exoscale-cli
base: core18
version: git
summary: The Exoscale command line tool
description: |
  The Exoscale command line tool.

  This snap allows you to use the "exo" command once installed, your
  gateway to the Exoscale platform.

  Usage: sudo snap install exoscale-cli; exo config; exo vm list

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

plugs:
  # This allows us to read/write in $HOME/.exoscale/*
  # It was granted via a forum post and is autoconnected.
  # Do not change the plug name.
  dot-exoscale:
    interface: personal-files
    write:
      - $HOME/.exoscale
      - $HOME/.cloudstack.ini

apps:
  # The app has an alias to "exo" that was granted via forum post.
  exoscale-cli:
    command: exo
    plugs:
      - network
      - home
      - dot-exoscale

parts:
  exo:
    # See 'snapcraft plugins'
    disable-parallel: True
    plugin: make
    source: .
    artifacts:
      - bin/exo
    build-snaps:
      - go
    build-packages:
      - git
    make-parameters: [build]
    override-build: |
      git submodule update --init --recursive go.mk
      snapcraftctl build
