name: release

on:
  workflow_dispatch: {}

permissions:
  contents: write

# TODO(sauterp) make a successful build a dependency
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/main.yml
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
