name: release

on:
  push:
    branches:
      - 'sauterp/sc-75094/gh-action-aur-release'
#    tags:
#      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    outputs:
      version_tag: ${{ steps.get-version-tag.outputs.version_tag }}
      linux_amd64_checksum: ${{ steps.get-linux-amd64-checksum.outputs.linux_amd64_checksum }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git submodule update --init --recursive go.mk
        shell: bash

      - run: echo "version_tag=$(make get-version-tag)" >> $GITHUB_OUTPUT
        id: get-version-tag
        shell: bash

      #TODO remove
      - run: mkdir dist && echo "816fcf0fa1c8acffa0bb557317a7f67f2657241783a20fcebcea408794f884c2  exoscale-cli_1.72.0_linux_amd64.tar.gz" > dist/exoscale-cli_1.72.0_checksums.txt
        shell: bash

      - run: echo "linux_amd64_checksum=$(grep '_linux_amd64.tar.gz' dist/exoscale-cli_*_checksums.txt | head -n 1 | cut -c1-64)" >> $GITHUB_OUTPUT
        id: get-linux-amd64-checksum
        shell: bash

#      - uses: ./.github/actions/build
#
#      - uses: ./go.mk/.github/actions/release
#        with:
#          release_github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
#          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
#          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}

  archrelease:
    needs: goreleaser

    runs-on: ubuntu-latest
    container: archlinux

    steps:
      - name: test arch linux
        run: |
          echo ${{ needs.goreleaser.outputs.version_tag }}
          echo ${{ steps.goreleaser.outputs.linux_amd64_checksum }}
        shell: bash

