name: release

on:
  push:
#TODO remove
    branches:
      - 'sauterp/sc-75094/gh-action-aur-release'
#TODO uncomment
#    tags:
#      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    outputs:
      version_tag: ${{ steps.get-version-tag.outputs.version_tag }}
      linux_amd64_checksum: ${{ steps.get-linux-amd64-checksum.outputs.linux_amd64_checksum }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #TODO remove
      - run: git submodule update --init --recursive go.mk
        shell: bash

#TODO uncomment
#      - uses: ./.github/actions/build
#
#      - uses: ./go.mk/.github/actions/release
#        with:
#          release_github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
#          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
#          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo "version_tag=$(make get-version-tag)" >> $GITHUB_OUTPUT
        id: get-version-tag
        shell: bash

      #TODO remove
      - run: mkdir dist && echo "816fcf0fa1c8acffa0bb557317a7f67f2657241783a20fcebcea408794f884c2  exoscale-cli_1.72.0_linux_amd64.tar.gz" > dist/exoscale-cli_1.72.0_checksums.txt
        shell: bash

      - run: echo "linux_amd64_checksum="$(grep -P 'exoscale-cli_[0-9]+\.[0-9]+\.[0-9]_linux_amd64.tar.gz' dist/exoscale-cli_*_checksums.txt | head -n 1 | cut -c1-64) >> $GITHUB_OUTPUT
        id: get-linux-amd64-checksum
        shell: bash

  archrelease:
    needs: goreleaser

    runs-on: ubuntu-latest
    container: archlinux

    steps:
      - name: test arch linux
        run: |
          echo ${{ needs.goreleaser.outputs.version_tag }}
          echo ${{ needs.goreleaser.outputs.linux_amd64_checksum }}
          useradd -G root runner
          mkdir /home/runner/
          chown -R runner /home/runner
        shell: bash

      - name: install tools
        run: pacman --noconfirm -Sy git openssh glibc
        shell: bash

      - name: Add SSH key
        run: |
            su runner
            cd /home/runner/
            mkdir -p /home/runner/.ssh
            ssh-keyscan aur.archlinux.org >> /home/runner/.ssh/known_hosts
            echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK
            ssh-add /home/runner/.ssh/github_actions
            git clone aur@aur.archlinux.org:exoscale-cli.git
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/home/runner/.ssh/known_hosts"
        shell: bash

      - name: makepkg
        run: |
          whoami
          su runner
          whoami
          cd /home/runner/exoscale-cli
          sed -i '/^pkgver=/s/.*/pkgver=${{ needs.goreleaser.outputs.version_tag }}/' PKGBUILD
          sed -i "/^sha256sums=/s/.*/sha256sums=\('${{ needs.goreleaser.outputs.linux_amd64_checksum }}'\)/" PKGBUILD
          makepkg
        shell: bash
