name: release

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

# TODO(sauterp) make a successful build a dependency
jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # TODO move this job to go.mk

      # TODO(sauterp) remove
      - run: git submodule update --init --recursive go.mk
        shell: bash

      # TODO(sauterp) reenable
      #- uses: ./.github/actions/build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-go@v3

      - name: Compute goreleaser cache key
        run: |
          echo "GORELEASER_CACHE_KEY=$(make --just-print install-goreleaser | tr --delete [:space:] | base32 --wrap 0)" >> $GITHUB_OUTPUT
        id: goreleaser-cache-key

      - name: Cache goreleaser
        id: cache-goreleaser
        uses: actions/cache@v3
        with:
          path: /home/runner/go/bin/goreleaser
          key: ${{ steps.goreleaser-cache-key.outputs.GORELEASER_CACHE_KEY }}

      - name: Install goreleaser
        if: steps.cache-goreleaser.outputs.cache-hit != 'true'
        run: make install-goreleaser
        shell: bash

      - run: echo "$(go env GOPATH)/bin/" >> $GITHUB_PATH
        shell: bash

      - run: make release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
