name: release

on:
  # TODO(sauterp) remove push trigger before merging
  push:
    branches:
      - sauterp/sc-42833/cli-release
  workflow_dispatch:

permissions:
  contents: write

# TODO(sauterp) make a successful build a dependency
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # TODO(sauterp) remove
      - run: git submodule update --init --recursive go.mk
        shell: bash
      # TODO(sauterp) reenable
      #- uses: ./.github/actions/build
      - run: |
          # TODO(sauterp) remove
          # counts the number of seconds since yesterday and sets it as the patch version in the git tag
          current=$(date +%s)
          yesterday=$(date -d "yesterday 00:00:00" +%s)
          difference=$((current - yesterday))
          git tag v1.70.$difference
        shell: bash
      - run: make install-goreleaser
        shell: bash
      - run: make release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
