name: release

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

# TODO(sauterp) make a successful build a dependency
jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # TODO move this job to go.mk

      # TODO(sauterp) remove
      - run: git submodule update --init --recursive go.mk
        shell: bash

      # TODO(sauterp) reenable
      #- uses: ./.github/actions/build

      - uses: ./go.mk/.github/actions/release
        with:
          release_github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          retistry_password: ${{ secrets.DOCKERHUB_TOKEN }}
