name: release

on:
  push:
    branches:
      - 'sauterp/sc-75094/gh-action-aur-release'
#    tags:
#      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    outputs:
      version_tag: ${{ steps.get-version-tag.outputs.version_tag }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git submodule update --init --recursive go.mk
        shell: bash

      - run: echo "version_tag=$(make get-version-tag)" >> $GITHUB_OUTPUT
        id: get-version-tag
        shell: bash
      
#      - uses: ./.github/actions/build
#
#      - uses: ./go.mk/.github/actions/release
#        with:
#          release_github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
#          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
#          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}

  archrelease:
    needs: goreleaser

    runs-on: ubuntu-latest
    container: archlinux

    steps:
    - name: test arch linux
      run: echo ${{ needs.goreleaser.outputs.version_tag }}
      shell: bash

