name: release

on:
  push:
    branches:
      - 'sauterp/sc-75094/gh-action-aur-release'
#    tags:
#      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

#      - uses: ./.github/actions/build
#
#      - uses: ./go.mk/.github/actions/release
#        with:
#          release_github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
#          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
#          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}

  archrelease:
    needs: goreleaser

    runs-on: ubuntu-latest
    container: archlinux

    steps:
    - name: test arch linux
      run: "pacman -h"
      shell: bash
