name: release

on:
  # TODO(sauterp) remove push trigger before merging
  push:
    branches:
      - sauterp/sc-42833/cli-release
  workflow_dispatch:

# TODO(sauterp) make a successful build a dependency
jobs:
  goreleaser:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      # TODO(sauterp) remove
      - run: git submodule update --init --recursive go.mk
        shell: bash
      # TODO(sauterp) reenable
      #- uses: ./.github/actions/build
      - run: |
          # TODO(sauterp) remove
          # counts the number of seconds since yesterday and sets it as the patch version in the git tag
          current=$(date +%s)
          yesterday=$(date -d "yesterday 00:00:00" +%s)
          difference=$((current - yesterday))
          git tag v1.70.$difference
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - uses: actions/setup-go@v3

      - name: Compute goreleaser cache key
        run: |
          echo "GORELEASER_CACHE_KEY=$(make --just-print install-goreleaser | tr --delete [:space:] | base32 --wrap 0)" >> $GITHUB_OUTPUT
        id: goreleaser-cache-key
      - name: Cache goreleaser
        id: cache-goreleaser
        uses: actions/cache@v3
        with:
          path: /home/runner/go/bin/goreleaser
          key: ${{ steps.goreleaser-cache-key.outputs.GORELEASER_CACHE_KEY }}
      - name: Install goreleaser
        if: steps.cache-goreleaser.outputs.cache-hit != 'true'
        run: make install-goreleaser
        shell: bash

      - run: echo "$(go env GOPATH)/bin/" >> $GITHUB_PATH
        shell: bash
      - run: make release
        shell: bash
        env:
          TAP_REPO_GITHUB_TOKEN: ${{ secrets.EXTENDED_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSWORD: ${{ secrets.PASSPHRASE }}
