name: release

on:
  # TODO(sauterp) remove push trigger before merging
  push:
    branches:
      - sauterp/sc-42833/cli-release
  workflow_dispatch:

permissions:
  contents: write

# TODO(sauterp) make a successful build a dependency
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # TODO(sauterp) reenable
      #- uses: ./.github/actions/build
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
