name: vuln

permissions: {}

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 7 * * 1' # 07:00 on Monday

jobs:
  run:
    name: Vuln
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          check-latest: true
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run govulncheck
        run: govulncheck -test ./...
